---

# Image settings https://github.com/docker-library/docs/tree/master/cassandra

# CASSANDRA_SEEDS -> specify ~3 seed nodes for dc.
# They are used by gossip for bootstrapping new nodes joining a cluster.

# Ports:
#    7000: intra-node communication
#    7001: TLS intra-node communication
#    7199: JMX
#    9042: CQL
#    9160: thrift service
#    9200: ElasticSearch HTTP
#    9300: ElasticSearch transport

version: '3.3'
services:

  elassandra:
    network_mode: host
    image: strapdata/elassandra:2.4.5.5
    volumes:
      - /opt/cyberfund/search/elassandra:/var/lib/cassandra
    environment:
       CASSANDRA_DC: LOCAL_DEVELOPMENT
       CASSANDRA_CLUSTER_NAME: CYBERNODE