apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -f chains-compose.yml -o chains-services.yaml
      kompose.version: 1.5.0 (999278f)
    creationTimestamp: null
    labels:
      io.kompose.service: abc
    name: abc
  spec:
    ports:
    - name: "7332"
      port: 7332
      targetPort: 7332
    selector:
      io.kompose.service: abc
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -f chains-compose.yml -o chains-services.yaml
      kompose.version: 1.5.0 (999278f)
    creationTimestamp: null
    labels:
      io.kompose.service: bitcoind
    name: bitcoind
  spec:
    ports:
    - name: "8332"
      port: 8332
      targetPort: 8332
    selector:
      io.kompose.service: bitcoind
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -f chains-compose.yml -o chains-services.yaml
      kompose.version: 1.5.0 (999278f)
    creationTimestamp: null
    labels:
      io.kompose.service: parity-etc
    name: parity-etc
  spec:
    ports:
    - name: "18545"
      port: 18545
      targetPort: 8545
    selector:
      io.kompose.service: parity-etc
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -f chains-compose.yml -o chains-services.yaml
      kompose.version: 1.5.0 (999278f)
    creationTimestamp: null
    labels:
      io.kompose.service: parity-eth
    name: parity-eth
  spec:
    ports:
    - name: "8545"
      port: 8545
      targetPort: 8545
    selector:
      io.kompose.service: parity-eth
  status:
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f chains-compose.yml -o chains-services.yaml
      kompose.version: 1.5.0 (999278f)
    creationTimestamp: null
    labels:
      io.kompose.service: abc
    name: abc
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: abc
      spec:
        containers:
        - args:
          - bitcoind
          - -server
          - -rest
          - -txindex
          - -rpcpassword=cyber
          - -rpcuser=cyber
          - -rpcallowip=::/0
          - -rpcport=7332
          image: hlebalbau/bitcoin-abc-docker:0.16.1
          name: abc
          ports:
          - containerPort: 7332
          resources: {}
          volumeMounts:
          - mountPath: /home/bitcoin/.bitcoin
            name: abc-claim0
        restartPolicy: Always
        volumes:
        - name: abc-claim0
          persistentVolumeClaim:
            claimName: abc-claim0
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: abc-claim0
    name: abc-claim0
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 500Gi
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f chains-compose.yml -o chains-services.yaml
      kompose.version: 1.5.0 (999278f)
    creationTimestamp: null
    labels:
      io.kompose.service: bitcoind
    name: bitcoind
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: bitcoind
      spec:
        containers:
        - args:
          - -server
          - -rest
          - -txindex
          - -rpcpassword=cyber
          - -rpcuser=cyber
          - -rpcallowip=0.0.0.0/0
          image: ruimarinho/bitcoin-core:0.15.1
          name: bitcoind
          ports:
          - containerPort: 8332
          resources: {}
          volumeMounts:
          - mountPath: /home/bitcoin/.bitcoin
            name: bitcoind-claim0
        restartPolicy: Always
        volumes:
        - name: bitcoind-claim0
          persistentVolumeClaim:
            claimName: bitcoind-claim0
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: bitcoind-claim0
    name: bitcoind-claim0
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 500Gi
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f chains-compose.yml -o chains-services.yaml
      kompose.version: 1.5.0 (999278f)
    creationTimestamp: null
    labels:
      io.kompose.service: parity-etc
    name: parity-etc
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: parity-etc
      spec:
        containers:
        - args:
          - --chain
          - classic
          - --db-path
          - /cyberdata
          - --jsonrpc-hosts
          - all
          - --jsonrpc-interface
          - all
          - --jsonrpc-threads
          - "8"
          image: parity/parity:stable
          name: parity-etc
          ports:
          - containerPort: 8545
          resources: {}
          volumeMounts:
          - mountPath: /cyberdata
            name: parity-etc-claim0
        restartPolicy: Always
        volumes:
        - name: parity-etc-claim0
          persistentVolumeClaim:
            claimName: parity-etc-claim0
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: parity-etc-claim0
    name: parity-etc-claim0
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 500Gi
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f chains-compose.yml -o chains-services.yaml
      kompose.version: 1.5.0 (999278f)
    creationTimestamp: null
    labels:
      io.kompose.service: parity-eth
    name: parity-eth
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: parity-eth
      spec:
        containers:
        - args:
          - --db-path
          - /cyberdata
          - --jsonrpc-hosts
          - all
          - --jsonrpc-interface
          - all
          - --jsonrpc-threads
          - "8"
          image: parity/parity:stable
          name: parity-eth
          ports:
          - containerPort: 8545
          resources: {}
          volumeMounts:
          - mountPath: /cyberdata
            name: parity-eth-claim0
        restartPolicy: Always
        volumes:
        - name: parity-eth-claim0
          persistentVolumeClaim:
            claimName: parity-eth-claim0
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: parity-eth-claim0
    name: parity-eth-claim0
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 500Gi
  status: {}
kind: List
metadata: {}

