version: '3.0'
services:

  cs-chain-pumps-btc:
    container_name: pump-btc
    image: cybernode/cs-chain-pumps:release-v1.0.0.RC5
    restart: unless-stopped
    environment:
      CASSANDRA_HOSTS: elassandra
      KAFKA_BROKERS: kafka-broker:9092
      CS_CHAINS_TO_PUMP: BITCOIN
      BITCOIND_URL: http://cyber:cyber@bitcoind:8332
      CS_LOG_LEVEL: INFO

  cs-chain-pumps-bth:
    container_name: pump-bth
    image: cybernode/cs-chain-pumps:release-v1.0.0.RC5
    restart: unless-stopped
    environment:
      CASSANDRA_HOSTS: elassandra
      KAFKA_BROKERS: kafka-broker:9092
      CS_CHAINS_TO_PUMP: BITCOIN_CASH
      ABC_URL: http://cyber:cyber@abc:7332
      CS_LOG_LEVEL: INFO

  cs-chain-pumps-eth:
    container_name: pump-eth
    image: cybernode/cs-chain-pumps:release-v1.0.0.RC5
    restart: unless-stopped
    environment:
      CASSANDRA_HOSTS: elassandra
      KAFKA_BROKERS: kafka-broker:9092
      CS_CHAINS_TO_PUMP: ETHEREUM
      PARITY_ETH_URL: http://parity-eth:8545
      CS_LOG_LEVEL: INFO

  cs-chain-pumps-etc:
    container_name: pump-etc
    image: cybernode/cs-chain-pumps:release-v1.0.0.RC5
    restart: on-failure
    environment:
      CASSANDRA_HOSTS: elassandra
      KAFKA_BROKERS: kafka-broker:9092
      CS_CHAINS_TO_PUMP: ETHEREUM_CLASSIC
      PARITY_ETC_URL: http://parity-etc:18545
      CS_LOG_LEVEL: INFO

  cs-address-service-btc:
    container_name: address-service
    image: cybernode/address-service:release-v1.0.0.RC5
    restart: unless-stopped
    environment:
      CS_CHAINS_TO_PUMP: BITCOIN,BITCOIN_CASH
      CASSANDRA_HOSTS: elassandra
      KAFKA_BROKERS: kafka-broker:9092
      CS_LOG_LEVEL: INFO

  cs-address-service-eth:
    container_name: address-service
    image: cybernode/address-service:release-v1.0.0.RC5
    restart: unless-stopped
    environment:
      CS_CHAINS_TO_PUMP: ETHEREUM,ETHEREUM_CLASSIC
      CASSANDRA_HOSTS: elassandra
      KAFKA_BROKERS: kafka-broker:9092
      CS_LOG_LEVEL: INFO