apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -f kafka-compose.yml -o kafka-services.yaml
      kompose.version: 1.5.0 (999278f)
    creationTimestamp: null
    labels:
      io.kompose.service: kafka-broker
    name: kafka-broker
  spec:
    ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
    - name: "1099"
      port: 1099
      targetPort: 1099
    selector:
      io.kompose.service: kafka-broker
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -f kafka-compose.yml -o kafka-services.yaml
      kompose.version: 1.5.0 (999278f)
    creationTimestamp: null
    labels:
      io.kompose.service: zoo
    name: zoo
  spec:
    ports:
    - name: "2181"
      port: 2181
      targetPort: 2181
    selector:
      io.kompose.service: zoo
  status:
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f kafka-compose.yml -o kafka-services.yaml
      kompose.version: 1.5.0 (999278f)
    creationTimestamp: null
    labels:
      io.kompose.service: kafka-broker
    name: kafka-broker
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: kafka-broker
      spec:
        containers:
        - env:
          - name: KAFKA_ADVERTISED_LISTENERS
            value: PLAINTEXT://kafka-broker:9092
          - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
            value: "true"
          - name: KAFKA_BROKER_ID
            value: "1"
          - name: KAFKA_DEFAULT_REPLICATION_FACTOR
            value: "1"
          - name: KAFKA_DELETE_TOPIC_ENABLE
            value: "true"
          - name: KAFKA_JMX_PORT
            value: "1099"
          - name: KAFKA_LOG4J_ROOT_LOGLEVEL
            value: WARN
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            value: "1"
          - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
            value: "1"
          - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
            value: "1"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zoo:2181
          image: confluentinc/cp-kafka:4.0.0
          name: kafka-broker
          ports:
          - containerPort: 9092
          - containerPort: 1099
          resources: {}
          volumeMounts:
          - mountPath: /var/lib/kafka
            name: kafka-broker-claim0
        restartPolicy: Always
        volumes:
        - name: kafka-broker-claim0
          persistentVolumeClaim:
            claimName: kafka-broker-claim0
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: kafka-broker-claim0
    name: kafka-broker-claim0
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 500Gi
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f kafka-compose.yml -o kafka-services.yaml
      kompose.version: 1.5.0 (999278f)
    creationTimestamp: null
    labels:
      io.kompose.service: zoo
    name: zoo
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: zoo
      spec:
        containers:
        - env:
          - name: KAFKA_LOG4J_ROOT_LOGLEVEL
            value: ERROR
          - name: ZOOKEEPER_CLIENT_PORT
            value: "2181"
          - name: ZOOKEEPER_TICK_TIME
            value: "2000"
          image: confluentinc/cp-zookeeper:4.0.0
          name: zoo
          ports:
          - containerPort: 2181
          resources: {}
          volumeMounts:
          - mountPath: /var/lib/zookeeper/data
            name: zoo-claim0
          - mountPath: /var/lib/zookeeper/log
            name: zoo-claim1
        restartPolicy: Always
        volumes:
        - name: zoo-claim0
          persistentVolumeClaim:
            claimName: zoo-claim0
        - name: zoo-claim1
          persistentVolumeClaim:
            claimName: zoo-claim1
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: zoo-claim0
    name: zoo-claim0
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: zoo-claim1
    name: zoo-claim1
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  status: {}
kind: List
metadata: {}

