apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -f search-compose.yml -o search-services.yaml
      kompose.service.type: loadbalancer
      kompose.version: 1.5.0 (999278f)
    creationTimestamp: null
    labels:
      io.kompose.service: cs-search-api
    name: cs-search-api
  spec:
    ports:
    - name: "80"
      port: 80
      targetPort: 10300
    selector:
      io.kompose.service: cs-search-api
    type: LoadBalancer
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -f search-compose.yml -o search-services.yaml
      kompose.service.type: loadbalancer
      kompose.version: 1.5.0 (999278f)
    creationTimestamp: null
    labels:
      io.kompose.service: cyber-ui
    name: cyber-ui
  spec:
    ports:
    - name: "80"
      port: 80
      targetPort: 80
    selector:
      io.kompose.service: cyber-ui
    type: LoadBalancer
  status:
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f search-compose.yml -o search-services.yaml
      kompose.service.type: loadbalancer
      kompose.version: 1.5.0 (999278f)
    creationTimestamp: null
    labels:
      io.kompose.service: cs-search-api
    name: cs-search-api
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: cs-search-api
      spec:
        containers:
        - env:
          - name: CASSANDRA_HOSTS
            value: elassandra
          - name: CORS_ALLOWED_ORIGINS
            value: '*'
          - name: CS_LOG_LEVEL
            value: INFO
          image: cybernode/cs-search-api:release-v1.0.0.RC6
          name: search-api
          ports:
          - containerPort: 10300
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f search-compose.yml -o search-services.yaml
      kompose.service.type: loadbalancer
      kompose.version: 1.5.0 (999278f)
    creationTimestamp: null
    labels:
      io.kompose.service: cyber-ui
    name: cyber-ui
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: cyber-ui
      spec:
        containers:
        - env:
          - name: CYBER_CHAINGEAR_API
            value: http://staging.cyber.fund:32600
          - name: CYBER_MARKETS_API
            value: http://staging.cyber.fund:32800
          - name: CYBER_SEARCH_API
            value: http://api.search.cyber.fund
          image: cybernode/cui-browser:latest
          name: cyber-ui
          ports:
          - containerPort: 80
          resources: {}
        restartPolicy: Always
  status: {}
kind: List
metadata: {}

