version: '3.0'
services:

  cs-search-api:
    container_name: search-api
    ports:
      - 80:10300
    image: cybernode/cs-search-api:release-v1.0.0.RC6
    restart: unless-stopped
    environment:
      CASSANDRA_HOSTS: elassandra
      CS_LOG_LEVEL: INFO
      CORS_ALLOWED_ORIGINS: "*"
    labels:
      kompose.service.type: loadbalancer

  cyber-ui:
    image: cybernode/cui-browser:latest
    ports:
      - 80:80
    environment:
      CYBER_CHAINGEAR_API: http://staging.cyber.fund:32600
      CYBER_SEARCH_API: http://api.search.cyber.fund
      CYBER_MARKETS_API: http://staging.cyber.fund:32800
    labels:
      kompose.service.type: loadbalancer
