global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: 'search-monitoring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8080','localhost:8081','docker.for.mac.localhost:8080','docker.for.mac.localhost:8081']