openapi: 3.0.1
components:
  schemas:

      Chain:
        type: string
        enum:
          - bitcoin
          - bitcoin_cash
          - ethereum
          - ethereum_classic

      ChainEntity:
        type: string
        enum:
          - block
          - tx
          - contract_summary
          - uncle